# Example configuration for remote Model Context Protocol (MCP) servers

# [[mcp.local_servers]]
# name = "filesystem"
# command = "npx" # command and arguments to start the MCP server
# args = [
#     "-y",
#     "@modelcontextprotocol/server-filesystem",
#     "~", # access to the home directory
# ]
# or: url = "http://localhost:3000" # if the server is already running

# [[mcp.remote_servers]]
# name = "example-mcp"
# url = "https://example-server.modelcontextprotocol.io/sse"

# authentication = "oauth2" # opens a browser window to authenticate on first use
# or: authentication = "none"
# or: authentication = "token", authorization_token = "<your-authorization-token>"

# Optional: restrict the tools that can be used with this MCP server
# authorization_token = "<your-authorization-token>"
# tool_configuration.enabled = true
# tool_configuration.allowed_tools = [
#   "example_tool_1",
#   "example_tool_2",
# ]
#
# [[mcp.remote_servers]]
# name = "another-mcp"
# ...
